surface
base_shader_ground
(
    string texture_path = "maps/ground.ACEScg.exr"
        [[ string description = "18% grey texture" ]]
)
{
    color base = texture(texture_path, u, 1 - v,
                        "colorspace", "ACEScg");
    
    normal Nn = normalize(N);
    Ci = base * diffuse(Nn);
    // normal Nn = normalize(N);
    // color vis = color(Nn.x, Nn.y, Nn.z) * 0.5 + color(0.5);
    // Ci = vis * diffuse(Nn);
}